# Server that the players get sent to when the server shuts down or a command is issued!
redirectServer: hub

# If you don't want a message sent leave blank.
# Leave this blank if you don't have LilyEssentials.
# This message will be sent to all servers when the plugin enables.
alertmessage: The creative server is now back online!

# Name of the server that this config is in.
servername: creative

# If you don't want a message sent leave blank.
# Leave this blank if you don't have LilyEssentials. 
# This message will be sent to all servers when the plugin disables.
shutdownalertmessage: The creative server has gone offline!

# Message that broadcasts to the server right before it is shutdown and players are sent.
broadcastmessage: The server is going offline for a restart to reduce lag! Please attempt to reconnect afterwards!

# Warning message to be sent that they are getting kicked to the hub server.
beforerestartmessage: The server is restarting in 3 seconds! You will be redirected to the lobby!
